// Portable from-scratch NIF writer. Requires nifly (ousnius/nifly, GPLv3).
// All visual geometry is generated by generate_reference_mesh.py, no NIF template.
#include <NifFile.hpp>
#include <bhk.hpp>
#include <ExtraData.hpp>
#include <cmath>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <vector>
using namespace nifly;
constexpr float SU=69.99125f;
constexpr uint32_t HeavyMetal=2229413539u;
static void require(bool cond,const char* text){if(!cond)throw std::runtime_error(text);}
int main(int argc,char**argv) try {
    require(argc==3,"usage: export_reference_nif mesh.cms output.nif");
    std::ifstream in(argv[1]);require(bool(in),"missing input");
    std::string magic;int version,nnode,nmesh,nhull;in>>magic>>version>>nnode>>nmesh>>nhull;
    require(magic=="CMSMESH"&&version==1&&nnode==17&&nhull==15,"unexpected geometry schema");
    NifFile nif; nif.Create(NiVersion::getSSE());auto&hdr=nif.GetHeader();
    auto replacement=std::make_unique<BSFadeNode>();*static_cast<NiNode*>(replacement.get())=*nif.GetRootNode();
    hdr.ReplaceBlock(nif.GetBlockID(nif.GetRootNode()),std::move(replacement));
    auto*root=nif.GetRootNode();std::vector<NiNode*> nodes;
    for(int i=0;i<nnode;i++){
        std::string name;int parent;MatTransform x;in>>name>>parent>>x.translation.x>>x.translation.y>>x.translation.z;x.translation*=SU;
        for(int r=0;r<3;r++)for(int c=0;c<3;c++)in>>x.rotation[r][c];
        NiNode*n;
        if(parent<0){n=root;n->name.get()=name;n->transform=x;}
        else{require(parent<i,"invalid node parent");n=nif.AddNode(name,x,nodes[parent]);}
        n->flags=14;nodes.push_back(n);
    }
    auto bsx=std::make_unique<BSXFlags>();bsx->name.get()="BSX";
    bsx->integerData=BSX_HAVOK|BSX_DYNAMIC|BSX_ARTICULATED|BSX_NEEDS_TRANSFORM_UPDATES;
    nif.AssignExtraData(root,std::move(bsx));
    // Vanilla iron/steel mace root metadata. Without Prn the engine may attach
    // the equipped model at the player root (feet), never the weapon hand.
    auto prn=std::make_unique<NiStringExtraData>();prn->name.get()="Prn";prn->stringData.get()="WeaponMace";
    nif.AssignExtraData(root,std::move(prn));
    uint64_t totalVerts=0,totalTriangles=0;
    for(int i=0;i<nmesh;i++){
        std::string name;int parent,mat;size_t nv,nt;in>>name>>parent>>mat>>nv>>nt;
        require(nv<65536&&nt<65536&&parent>=0&&parent<nnode&&mat>=0&&mat<11,"invalid mesh");
        std::vector<Vector3> v(nv),n(nv);std::vector<Vector2>uv(nv);std::vector<Triangle>t(nt);
        for(size_t j=0;j<nv;j++){in>>v[j].x>>v[j].y>>v[j].z>>n[j].x>>n[j].y>>n[j].z>>uv[j].u>>uv[j].v;v[j]*=SU;uv[j].v=1-uv[j].v;}
        for(auto& tri:t){unsigned a,b,c;in>>a>>b>>c;require(a<nv&&b<nv&&c<nv,"bad index");tri=Triangle(a,b,c);}
        require(bool(in),"truncated mesh");auto*shape=nif.CreateShapeFromData(name,&v,&t,&uv,&n);require(shape,"mesh create failed");
        nif.SetParentNode(shape,nodes[parent]);shape->flags=14;
        auto*sh=dynamic_cast<BSLightingShaderProperty*>(nif.GetShader(shape));require(sh,"missing shader");
        bool metal=mat!=1&&mat!=2&&mat!=5;
        sh->shaderFlags1=SLSF1_SPECULAR|SLSF1_ZBUFFER_TEST|SLSF1_CAST_SHADOWS|SLSF1_RECEIVE_SHADOWS;
        sh->shaderFlags2=SLSF2_ZBUFFER_WRITE;
        sh->glossiness=metal?28.f:(mat==1?8.f:13.f);sh->specularStrength=metal?.75f:(mat==1?.18f:.28f);
        sh->specularColor=Vector3(.78f,.79f,.8f);
        if(metal){sh->SetShaderType(BSLSP_ENVMAP);sh->shaderFlags1|=SLSF1_ENVIRONMENT_MAPPING;sh->environmentMapScale=.45f;}
        if(mat==3){sh->environmentMapScale=.16f;sh->specularStrength=.45f;}
        if(mat==4){sh->environmentMapScale=.72f;sh->glossiness=38.f;}
        static const char* bases[]={"metal","wood","leather","metal","metal","cord","metal","spike","chain","ring","emblem"};
        std::string base=bases[mat];
        std::string prefix="textures\\weapons\\ChainMorningstarVR\\cms_"+base;
        std::string path=prefix+"_d.dds";nif.SetTextureSlot(shape,path,0);path=prefix+"_n.dds";nif.SetTextureSlot(shape,path,1);
        if(metal){path="textures\\cubemaps\\ShinyDull_e.dds";nif.SetTextureSlot(shape,path,4);path=prefix+"_m.dds";nif.SetTextureSlot(shape,path,5);}
        Color4 tint(1,1,1,1);
        if(mat==3)tint=Color4(.30f,.32f,.35f,1);

        if(mat==6)tint=Color4(1,.76f,.44f,1);
        if(mat==3||mat==6){nif.SetColorsForShape(shape,std::vector<Color4>(nv,tint));sh->shaderFlags2|=SLSF2_VERTEX_COLORS;}
        nif.CalcTangentsForShape(shape);totalVerts+=nv;totalTriangles+=nt;
    }
    auto list=std::make_unique<bhkListShape>();list->SetMaterial(HeavyMetal);
    for(int i=0;i<nhull;i++){
        unsigned nv,np;float margin;in>>nv>>np>>margin;require(nv>=4&&nv<256&&np>=4&&np<256,"invalid convex hull");
        auto hull=std::make_unique<bhkConvexVerticesShape>();hull->SetMaterial(HeavyMetal);hull->radius=margin;
        for(unsigned j=0;j<nv;j++){Vector4 p;in>>p.x>>p.y>>p.z;p.w=0;hull->verts.push_back(p);}
        for(unsigned j=0;j<np;j++){Vector4 p;in>>p.x>>p.y>>p.z>>p.w;hull->normals.push_back(p);}
        list->subShapeRefs.AddBlockRef(hdr.AddBlock(std::move(hull)));
        HavokFilter f;f.layer=5;list->filters.push_back(f);
    }
    require(bool(in),"truncated hulls");
    // The engine and HIGGS expect a body on the weapon ROOT. A transformed
    // body keeps all fifteen hulls in head-local coordinates, with its authored
    // offset at the iron ball. CMS clones the shape and drives it independently.
    MatTransform headRest;require(nif.GetNodeTransformToGlobal("CMS_HeadNode",headRest),"missing head transform");
    const Matrix3 expectedHeadRotation(1,0,0, 0,0,1, 0,-1,0);
    for(int r=0;r<3;r++)for(int c=0;c<3;c++)
        require(std::fabs(headRest.rotation[r][c]-expectedHeadRotation[r][c])<1e-5f,"unexpected head rest basis");
    auto body=std::make_unique<bhkRigidBodyT>();body->shapeRef.index=hdr.AddBlock(std::move(list));
    body->translation=Vector4(headRest.translation.x/SU,headRest.translation.y/SU,headRest.translation.z/SU,0);
    body->rotation=QuaternionXYZW(-std::sqrt(.5f),0,0,std::sqrt(.5f));
    body->mass=8;body->friction=.74f;body->restitution=.08f;body->linearDamping=.12f;body->angularDamping=.2f;
    body->inertiaMatrix[0]=body->inertiaMatrix[5]=body->inertiaMatrix[10]=.4f*8*.16f*.16f;
    body->collisionFilter.layer=5;body->collisionFilterCopy=body->collisionFilter;
    body->broadPhaseType=1;body->motionSystem=2;body->qualityType=4;body->solverDeactivation=2;
    body->penetrationDepth=.01f;
    auto collision=std::make_unique<bhkCollisionObject>();collision->flags=129;collision->targetRef.index=nif.GetBlockID(root);collision->bodyRef.index=hdr.AddBlock(std::move(body));
    root->collisionRef.index=hdr.AddBlock(std::move(collision));
    require(nif.Save(argv[2])==0,"NIF save failed");
    NifFile check;require(check.Load(argv[2])==0,"roundtrip load failed");require(check.IsSSECompatible()&&!check.HasUnknown(),"invalid Skyrim SE/VR NIF");
    auto*head=check.FindBlockByName<NiNode>("CMS_HeadNode");require(head,"lost head node");
    unsigned prnCount=0;
    for(auto* extra:check.GetChildren<NiStringExtraData>(check.GetRootNode(),true))
        if(extra->name.get()=="Prn"){require(extra->stringData.get()=="WeaponMace","incorrect weapon attachment");++prnCount;}
    require(prnCount==1,"missing/duplicate root Prn attachment");
    require(head->collisionRef.index==0xFFFFFFFFu,"visual head must not own a competing native body");
    auto*co=check.GetHeader().GetBlock<bhkCollisionObject>(check.GetRootNode()->collisionRef.index);require(co,"lost root collision");
    require(co->targetRef.index==check.GetBlockID(check.GetRootNode()),"collision must target weapon root");
    auto*rb=check.GetHeader().GetBlock<bhkRigidBodyT>(co->bodyRef.index);require(rb,"lost transformed root body");
    require(std::fabs(rb->translation.y-headRest.translation.y/SU)<1e-5f&&
        std::fabs(rb->rotation.x+std::sqrt(.5f))<1e-5f,"lost rest head collision transform");
    auto*cl=check.GetHeader().GetBlock<bhkListShape>(rb->shapeRef.index);require(cl&&cl->subShapeRefs.GetSize()==15,"lost compound hulls");
    require(check.GetShapes().size()==size_t(nmesh),"lost geometry");
    for(int i=0;i<14;i++){char name[40];snprintf(name,sizeof name,"CMS_LinkNode_%02d",i);auto*ln=check.FindBlockByName<NiNode>(name);require(ln,"lost chain node");}
    std::cout<<"NIF_ROUNDTRIP_PASS nodes="<<check.GetNodes().size()<<" meshes="<<check.GetShapes().size()<<" vertices="<<totalVerts<<" triangles="<<totalTriangles<<" convex_hulls=15\n";
    std::cout<<"WEAPON_ATTACHMENT_PASS Prn=WeaponMace root_collision=bhkRigidBodyT head_local_hulls=15\n";
    std::cout<<"IN_GAME_VALIDATION_PENDING: NIF parsing proves file structure, not Skyrim runtime stability.\n";
    return 0;
}catch(const std::exception&e){std::cerr<<"NIF_BUILD_FAIL: "<<e.what()<<'\n';return 1;}
