#!/usr/bin/env python3
"""Export the actual CMS NIF collision planes for CPU weapon-triangle queries.

Run after generate_reference_mesh.py. --check is a release gate: runtime contact
planes must equal the same CMS interchange that is used to create the NIF.
Margins are intentionally excluded: confirmed intersections are a strict subset
of the native Havok shape, never an inflated broadphase sphere.
"""
import argparse
import hashlib
from pathlib import Path


def export(source: Path) -> str:
    rows = source.read_text().splitlines()
    assert rows[0] == 'CMSMESH 1'
    nodes, meshes, hulls = map(int, rows[1].split())
    pos = 2 + nodes
    for _ in range(meshes):
        fields = rows[pos].split()
        pos += 1 + int(fields[3]) + int(fields[4])
    planes, ranges, canonical = [], [], []
    for _ in range(hulls):
        nv, np, margin = rows[pos].split()
        pos += 1
        vertices = [' '.join(f'{round(float(v), 8):.9g}' for v in r.split()) for r in rows[pos:pos+int(nv)]]
        pos += int(nv)
        selected = [' '.join(f'{round(float(v), 8):.9g}' for v in r.split()) for r in rows[pos:pos+int(np)]]
        pos += int(np)
        ranges.append((len(planes),len(selected)))
        planes.extend(selected)
        canonical.extend([f'{nv} {np} {margin}',*vertices,*selected])
    assert pos == len(rows) and hulls == 15
    digest = hashlib.sha256(('\n'.join(canonical)+'\n').encode()).hexdigest()
    def flt(s):
        if '.' not in s and 'e' not in s.lower():
            s += '.0'
        return s+'f'
    out = ['#pragma once', '', '// Generated by Source/NIF/export_contact_planes.py; do not hand edit.',
           '// Native margins excluded; canonical coefficients are inset by 0.1 micrometre.',
           '#include <array>', '#include <cstdint>', '#include "ChainPhysicsCore.hpp"', '',
           'namespace cms::weaponmesh {', 'struct Plane { Vec3 normal; float distance; };',
           'struct HullRange { std::uint16_t start; std::uint16_t count; };',
           f'inline constexpr char kCollisionHullDigest[] = "{digest}";',
           f'inline constexpr std::array<Plane, {len(planes)}> kHeadPlanes = {{{{']
    for p in planes:
        tokens = p.split()
        tokens[3] = f'{float(tokens[3]) + 1e-7:.9g}'
        vals = [flt(s) for s in tokens]
        out.append('    {{'+', '.join(vals[:3])+'}, '+vals[3]+'},')
    out += ['}};', f'inline constexpr std::array<HullRange, {len(ranges)}> kHeadHulls = {{{{']
    out.extend(f'    {{{start}, {count}}},' for start,count in ranges)
    out += ['}};', '} // namespace cms::weaponmesh', '']
    return '\n'.join(out)


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('source', type=Path)
    p.add_argument('--header', type=Path, default=Path(__file__).resolve().parents[1]/'SKSE'/'HeadContactPlanes.hpp')
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    content = export(args.source)
    if args.check:
        assert args.header.read_text() == content, 'Native head collision planes changed; regenerate header and rebuild DLL.'
        print('WEAPON_CONTACT_PLANES_PASS 15 exact native convex hulls')
    else:
        args.header.write_text(content)
        print(args.header)
